{% set version = "0.3-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qualv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qualV_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qualV/qualV_{{ version }}.tar.gz
  sha256: e60825afab3de2b1cb257c55dfc380d1448962e429df180b2add104752771827

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-kernsmooth
  run:
    - r-base
    - r-kernsmooth

test:
  commands:
    - $R -e "library('qualV')"           # [not win]
    - "\"%R%\" -e \"library('qualV')\""  # [win]

about:
  home: http://qualV.R-Forge.R-Project.org/
  license: GPL-2.0-or-later
  summary: Qualitative methods for the validation of dynamic models. It contains (i) an orthogonal set of deviance measures for absolute, relative and ordinal scale and (ii) approaches accounting for time shifts. The first approach transforms time to take time delays and speed differences into account. The second divides
    the time series into interval units according to their main features and finds the longest common subsequence (LCS) using a dynamic programming algorithm.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: qualV
# Title: Qualitative Validation Methods
# Version: 0.3-3
# Authors@R: c(person("K. Gerald", "van den Boogaart", role = c("aut", "ths")), person("Stefanie", "Rost", role = "aut"), person("Thomas", "Petzoldt", role = c("aut", "ths", "cre"), email = "thomas.petzoldt@tu-dresden.de"))
# Description: Qualitative methods for the validation of dynamic models. It contains (i) an orthogonal set of deviance measures for absolute, relative and ordinal scale and (ii) approaches accounting for time shifts. The first approach transforms time to take time delays and speed differences into account. The second divides the time series into interval units according to their main features and finds the longest common subsequence (LCS) using a dynamic programming algorithm.
# Maintainer: Thomas Petzoldt <thomas.petzoldt@tu-dresden.de>
# Depends: R (>= 2.0.0), KernSmooth
# Imports: graphics, grDevices, stats, utils
# License: GPL (>= 2)
# URL: http://qualV.R-Forge.R-Project.org/
# NeedsCompilation: yes
# Packaged: 2017-06-12 20:01:45 UTC; thpe
# Author: K. Gerald van den Boogaart [aut, ths], Stefanie Rost [aut], Thomas Petzoldt [aut, ths, cre]
# Repository: CRAN
# Date/Publication: 2017-06-12 23:22:19 UTC
